# Generated by Django 5.2.1 on 2025-07-03 23:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membership',
        ),
        migrations.AddField(
            model_name='client',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='client',
            name='membership_type',
            field=models.CharField(choices=[('D', 'Diario'), ('M', 'Mensual'), ('T', 'Trimestral'), ('A', 'Anual')], default='M'),
        ),
        migrations.AddField(
            model_name='client',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
