# Generated by Django 5.2.1 on 2025-07-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_membership_client_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
