# Generated by Django 5.2.1 on 2025-05-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_address_alter_user_dni_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='monthly',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='one_year',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='tree_months',
        ),
        migrations.AddField(
            model_name='membership',
            name='time',
            field=models.CharField(choices=[('M', 'Mensual'), ('T', 'Trimestral'), ('A', 'Anual')], default='M', max_length=3),
            preserve_default=False,
        ),
    ]
