# Generated by Django 5.2.1 on 2025-07-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodels',
            old_name='admind_id',
            new_name='admind',
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='article',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postmodels',
            name='offers',
            field=models.CharField(max_length=255),
        ),
    ]
