# Generated by Django 5.2.1 on 2025-07-13 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_admind_id_postmodels_admind_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodels',
            old_name='admind',
            new_name='admin',
        ),
    ]
