# Generated by Django 5.2.1 on 2025-07-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_admind_postmodels_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
