# Generated by Django 5.2.1 on 2025-07-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_cashsession_cashtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsession',
            name='discrepancy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='expected_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
